spring:
  application:
    name: random-researcher-agent-spring
  ai:
    mcp:
      client:
        type: SYNC
        sse:
          connections:
            content:
              url: http://localhost:8081
              sse-endpoint: /sse
            output:
              url: http://localhost:8082
              sse-endpoint: /sse

app:
  openrouter:
    base-url: https://openrouter.ai/api
    api-key: 
    # model: nvidia/nemotron-3-nano-30b-a3b:free
    model: stepfun/step-3.5-flash:free
    temperature: 0.1
    logprobs: false
    http-headers:
      HTTP-Referer: http://localhost
      X-Title: Random Researcher

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web.client: DEBUG
